packages:
  - apps/*
  - packages/*
  - ../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-gateway/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-gateway/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../kb-labs-core/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../kb-labs-core/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../kb-labs-core/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../kb-labs-studio/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/../kb-labs-studio/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-gateway/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-gateway/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../../infra/kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../kb-labs-shared/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../kb-labs-shared/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/packages/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../../infra/kb-labs-plugin/packages/*
  - ../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../../infra/kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/apps/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/apps/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-studio/apps/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-studio/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-devkit
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-devkit
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/apps/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/packages/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-gateway/apps/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-gateway/packages/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/../../infra/kb-labs-devkit
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/../kb-labs-shared/apps/*
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/../kb-labs-shared/packages/*
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/apps/*
  - ../kb-labs-core/../kb-labs-shared/../kb-labs-core/packages/*
  - ../kb-labs-core/../kb-labs-shared/apps/*
  - ../kb-labs-core/../kb-labs-shared/packages/*
  - ../kb-labs-core/apps/*
  - ../kb-labs-core/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/../kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/apps/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-core/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-studio/apps/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/../kb-labs-studio/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../kb-labs-gateway/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/../kb-labs-gateway/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/../kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/../kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-core/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../kb-labs-core/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../kb-labs-core/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../kb-labs-core/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../kb-labs-studio/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/../kb-labs-studio/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/../kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../kb-labs-cli/apps/*
  - ../kb-labs-rest-api/../kb-labs-cli/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-core/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../../platform/kb-labs-studio/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-gateway/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/../kb-labs-gateway/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../../infra/kb-labs-plugin/packages/plugin-adapters/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../kb-labs-core/../kb-labs-devkit
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../kb-labs-core/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../kb-labs-core/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../kb-labs-studio/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/../kb-labs-studio/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/../kb-labs-shared/packages/*
  - ../kb-labs-rest-api/../kb-labs-core/apps/*
  - ../kb-labs-rest-api/../kb-labs-core/packages/*
  - ../kb-labs-rest-api/apps/*
  - ../kb-labs-rest-api/packages/*
