import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { cn } from '../lib/utils';
const KBDialog = DialogPrimitive.Root;
const KBDialogTrigger = DialogPrimitive.Trigger;
const KBDialogPortal = DialogPrimitive.Portal;
const KBDialogClose = DialogPrimitive.Close;
const KBDialogOverlay = React.forwardRef(({ className, ...props }, ref) => (_jsx(DialogPrimitive.Overlay, { ref: ref, className: cn('fixed inset-0 z-50 bg-black/80 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0', className), ...props })));
KBDialogOverlay.displayName = DialogPrimitive.Overlay.displayName;
const KBDialogContent = React.forwardRef(({ className, children, ...props }, ref) => (_jsxs(KBDialogPortal, { children: [_jsx(KBDialogOverlay, {}), _jsx(DialogPrimitive.Content, { ref: ref, className: cn('fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] rounded-lg', className), ...props, children: children })] })));
KBDialogContent.displayName = DialogPrimitive.Content.displayName;
const KBDialogHeader = ({ className, ...props }) => (_jsx("div", { className: cn('flex flex-col space-y-1.5 text-center sm:text-left', className), ...props }));
KBDialogHeader.displayName = 'KBDialogHeader';
const KBDialogFooter = ({ className, ...props }) => (_jsx("div", { className: cn('flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2', className), ...props }));
KBDialogFooter.displayName = 'KBDialogFooter';
const KBDialogTitle = React.forwardRef(({ className, ...props }, ref) => (_jsx(DialogPrimitive.Title, { ref: ref, className: cn('text-lg font-semibold leading-none tracking-tight', className), ...props })));
KBDialogTitle.displayName = DialogPrimitive.Title.displayName;
const KBDialogDescription = React.forwardRef(({ className, ...props }, ref) => (_jsx(DialogPrimitive.Description, { ref: ref, className: cn('text-sm text-gray-500 dark:text-gray-400', className), ...props })));
KBDialogDescription.displayName = DialogPrimitive.Description.displayName;
export { KBDialog, KBDialogPortal, KBDialogOverlay, KBDialogTrigger, KBDialogClose, KBDialogContent, KBDialogHeader, KBDialogFooter, KBDialogTitle, KBDialogDescription, };
//# sourceMappingURL=kb-dialog.js.map